name: io_scene_srally2mdl Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Create "io_scene_srally2mdl ZIP"
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'io_scene_srally2mdl.zip'
        directory: 'src'
        exclusions: '*.git* *SR2Tools/Documentation* *SR2Tools/GUIbackend* *Changelog.txt *GUI_Run.py *README.md *SARCextractor.py *conversion.py *bin_files_tool.py *bmp_handler.py *bmp_png_conversion.py *color_conversion.py *exe_dll_patcher.py *texture_classes.py *texture_tool.py *unyakuza.py'
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        path: src/io_scene_srally2mdl.zip
        archive: false
